[build]
  command = "ng build --configuration=production"
  publish = "dist/ronit-portfolio0"

[build.environment]
  NODE_VERSION = "25.2.1"
  NPM_VERSION = "11.6.2"
  NG_CLI_ANALYTICS = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

    [forms]
  detection = "enabled"